Fix Steam API request error log
at line 34 we're trying to concatenate int to str which is imposiible

```
Error fetching datacan only concatenate str (not "int") to str
Traceback (most recent call last):
  File "/Users/crd5/Projects/aw-watcher-steam/.venv/lib/python3.13/site-packages/aw_watcher_steam/main.py", line 53, in main
    game_data = get_currently_played_games(api_key=api_key,steam_id=steam_id)
  File "/Users/crd5/Projects/aw-watcher-steam/.venv/lib/python3.13/site-packages/aw_watcher_steam/main.py", line 34, in get_currently_played_games
    raise Exception("Steam API request error, error code:" + response.status_code + " " + response.text)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "int") to str
```